delete from user;
delete from product;
delete from role;
delete from whole_order;
delete from order_item;
INSERT INTO user (user_id, first_name, last_name, email, password) VALUES (1, 'Elizabeth', 'Sajdak', 'esajdak@madisoncollege.edu', 'password');
INSERT INTO user (user_id, first_name, last_name, email, password) VALUES (2, 'Kyle', 'Kelley', 'kk@gmail.com', 'password');
INSERT INTO order_item (id, order_number, item_id, quantity) VALUES (1, 1, 5, 1);
INSERT INTO order_item (id, order_number, item_id, quantity) VALUES (2, 1, 4, 2);
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (1, 1, '2020Ornaments.jpg', '2020 Wooden Ornaments with white ribbon', '#ornaments #christmas', '$1', '$5', 0, '2020 Wooden Ornaments');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (2, 1, 'shotGlasses.jpg', 'Set of 3 holiday shot glasses perfect for showing your holiday spirit!', '#shotglasses #glasses #shots', '$2', '$10', 0, 'Holiday Shot Glasses');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (3, 1, 'customShirts.jpg', 'Custom Made Shirts', '#shirt', '$8', '$20', 1, 'Custom Shirts');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (4, 1, 'halloweenShotGlasses.jpg', 'Set of 6 scary movie character shot glasses', '#shotglasses #shots #glasses', '$4', '$10', 0, 'Halloween Shot Glasses');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (5, 1, 'halloweenWineGlass.jpg', 'Here for the boos wine glass', '#wine #glasses', '$1', '$6', 0, 'Halloween Wine Glass');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (6, 1, 'koiShirt.jpg', 'Red and black koi fish shirt', '#shirt', '$5', '$15', 0, 'Koi Shirt');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (7, 1, 'nameOrnaments.jpg', 'Custom name ornaments', '#ornaments #christmas', '$2', '$10', 1, 'Custom Name Ornaments');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (8, 1, 'potHolders.jpg', 'Your choice of potholder, you can pick the color as well.', '#christmas #potholders', '$2', '$8', 1, 'Pot Holders');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (9, 1, 'santaBuckets.jpg', 'Custom santa buckets.', '#santa #christmas', '$2', '$6', 1, 'Custom Santa Buckets');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (10, 1, 'skullShotGlasses.jpg', 'Set of 6 skull shot glasses', '#shotglasses #shots #glasses', '$4', '$15', 0, 'Skull Shot Glasses');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (11, 1, 'treeTile.jpg', 'Holiday tree tile', '#trees #christmas #decor', '$1', '$12', 0, 'Holiday Tree Tile');
INSERT INTO product (item_id, user_id, image, description, tags, production_cost, price, customizable, title) VALUES (12, 1, 'wisconsinMug.jpg', 'Wisconsin mug with a heart in Madison, can move the heart to any city', '#glass #mug #wisconsin', '$2', '$8', 1, 'Wisconsin Mug');
INSERT INTO whole_order (order_number, user_id) VALUES (1, 1);INSERT INTO role (id, role_name, email, user_id) VALUES (1, 'admin', 'esajdak@madisoncollege.edu', 1);
INSERT INTO role (id, role_name, email, user_id) VALUES (2, 'all', 'kk@gmail.com', 2);